steps:
  # Step 1: Install dependencies and run tests in one step
  - name: 'python:3.12'
    id: 'Install and Run Tests'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install playwright
        python -m playwright install --with-deps chromium
        pytest --html=reports/index.html

options:
  machineType: 'E2_HIGHCPU_8'  # Adjust based on test load
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s  # Increase timeout if needed
