steps:
  # Step 1: Set up Python environment
  - name: 'python:3.12'
    id: 'Install dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'python:3.12'
    id: 'Install Playwright'
    entrypoint: 'pip'
    args: ['install', 'playwright']

  # Step 2: Install Playwright browsers
  - name: 'python:3.12'
    id: 'Install Playwright Browsers'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'playwright install --with-deps chromium'

  # Step 3: Run Playwright tests
  - name: 'python:3.12'
    id: 'Run Tests'
    entrypoint: 'pytest'
    args: ['--html=reports/index.html']  # Modify based on your test directory

options:
  machineType: 'E2_HIGHCPU_8'  # Adjust based on test load
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s  # Increase timeout if needed
